version: '3'

services:
    bemodule:
      container_name: budget.ms.budgetcontrol.cloud
      image: mlabfactory/php8-fpm:v1.0
      volumes:
        - ./:/var/www/workdir
      networks:
        - budgetcontrol_network
      restart: unless-stopped

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
