version: '2.2'

services:
    bemodule:
      container_name: budgetcontrol-ms-budget
      image: mlabfactory/php8-apache:v1.2.1-xdebug
      ports:
        - "8084:80" # Change port do container
      restart: unless-stopped
      volumes:
        - ./:/var/www/workdir
      networks:
        - budgetcontrol_network

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
